obj-y			+= cache.o
obj-y			+= clk.o
obj-$(CONFIG_DEBUG)	+= debug.o
obj-y			+= head.o
obj-y			+= main.o
obj-y			+= next-entry.o
obj-y			+= pinctrl.o
obj-y			+= printk.o
obj-y			+= soc-info.o
obj-y			+= uart.o

extra-y			+= uniphier.lds
