# SPDX-License-Identifier: GPL-2.0-only

obj-y				+= memconf.o
obj-$(CONFIG_SOC_LD11)		+= umc-ld11.o
obj-$(CONFIG_SOC_LD20)		+= umc-ld20.o
obj-$(CONFIG_SOC_PXS3)		+= umc-pxs3.o
obj-$(CONFIG_SOC_NX1)		+= umc-nx1.o
obj-$(CONFIG_DRAM_SCRAMBLE)	+= umc-scramble.o
